
#######

//Start recording on all configured plugins
GET http://net_core_tpm:8081/api/protocols/*/plugins/record-plugin/start

#######

//Stop recording on all configured plugins
GET http://net_core_tpm:8081/api/protocols/*/plugins/record-plugin/stop

#######

//Download all results
GET http://net_core_tpm:8081/api/storage/download

#######

//Stop mysql container and call this to replay only mysql
GET http://net_core_tpm:8081/api/protocols/mysql-01/plugins/replay-plugin/start

#######

//Stop all replaying
GET http://net_core_tpm:8081/api/protocols/*/plugins/replay-plugin/stop

#######

//Stop rest server container and call this to replay all rest calls
GET http://net_core_tpm:8081/api/protocols/http-01/plugins/replay-plugin/start

#######

//Stop all replaying
GET http://net_core_tpm:8081/api/protocols/*/plugins/replay-plugin/stop

#######

