version: '3.8'
services:
  net_core_tpm:
    build:
      context: Tpm/.
      dockerfile: Dockerfile.test
    image: "net_core_tpm"
    container_name: net_core_tpm
    ports:
      - '28081:8081'
      - '29000:9000'
      - '20080:80'
    depends_on:
      db_mysql:
        condition: service_started
  net_core_http:
    build:
      context: HttpServer/.
      dockerfile: Dockerfile
    image: "net_core_http"
    container_name: net_core_http
    depends_on:
      net_core_tpm:
        condition: service_healthy
  net_core_rest:
    build:
      context: RestServer/.
      dockerfile: Dockerfile
    image: "net_core_rest"
    container_name: net_core_rest
    depends_on:
      net_core_tpm:
        condition: service_healthy
  db_mysql:
    build:
      context: MySQL/.
      dockerfile: Dockerfile
    container_name: db_mysql
    image: "tpm_mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '23306:3306'