version: '3.8'
services:
  go-postgres:
    build:
      context: Postgres/.
      dockerfile: Dockerfile
    container_name: go-postgres
    image: "go-postgres"
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: 'password'
    ports:
      - '25432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres'] # <<<---
      interval: 1s
      timeout: 5s
      retries: 10
  go-redis:
    image: "redis:6.2-alpine"
    container_name: go-redis
    restart: always
    ports:
      - '26379:6379'
    command: redis-server --save 20 1 --loglevel warning