version: '3.8'
services:
  java_tpm:
    build:
      context: Tpm/.
      dockerfile: Dockerfile
    image: "java_tpm"
    container_name: java_tpm
    ports:
      - '28081:8081'
      - '29000:9000'
      - '20080:80'
    depends_on:
      db_mysql_java:
        condition: service_started
      mosquitto_tpm:
        condition: service_started
  java_rest:
    build:
      context: RestServer/.
      dockerfile: Dockerfile
    image: "java_rest"
    container_name: java_rest
    depends_on:
      java_tpm:
        condition: service_healthy
  java_quote_generator:
    build:
      context: QuoteGenerator/.
      dockerfile: Dockerfile
    image: "java_quote_generator"
    container_name: java_quote_generator
    depends_on:
      java_rest:
        condition: service_healthy
  java_http:
    build:
      context: HttpServer/.
      dockerfile: Dockerfile
    image: "java_http"
    container_name: java_http
    depends_on:
      java_rest:
        condition: service_healthy
  db_mysql_java:
    build:
      context: MySQL/.
      dockerfile: Dockerfile
    container_name: db_mysql_java
    image: "tpm_mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '23306:3306'
  mosquitto_tpm:
    build:
      context: Mosquitto/.
      dockerfile: Dockerfile
    image: "mosquitto_tpm"
    container_name: mosquitto_tpm
    ports:
      - '1883:1883'