version: '3.8'
services:
  java-tpm:
    build:
      context: Tpm/.
      dockerfile: Dockerfile.test
    image: "java-tpm"
    container_name: java-tpm
    ports:
      - '31883:1883'
      - '33306:3306'
      - '28081:8081'
      - '29000:9000'
      - '20080:80'
    depends_on:
      java-mysql:
        condition: service_started
      java-mosquitto:
        condition: service_started
  java-rest:
    build:
      context: RestServer/.
      dockerfile: Dockerfile
    image: "java-rest"
    container_name: java-rest
    depends_on:
      java-mysql:
        condition: service_started
      java-tpm:
        condition: service_healthy
      java-mosquitto:
        condition: service_started
  java-quote-generator:
    build:
      context: QuoteGenerator/.
      dockerfile: Dockerfile
    image: "java-quote-generator"
    container_name: java-quote-generator
    depends_on:
      java-rest:
        condition: service_healthy
      java-mosquitto:
        condition: service_started
  java-mysql:
    build:
      context: MySQL/.
      dockerfile: Dockerfile
    container_name: java-mysql
    image: "java-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '23306:3306'
  java-mosquitto:
    build:
      context: Mosquitto/.
      dockerfile: Dockerfile
    image: "java-mosquitto"
    container_name: java-mosquitto
    ports:
      - '21883:1883'