version: '3.8'
services:
  net_core_tpm:
    build:
      context: Tpm/.
      dockerfile: Dockerfile.test
    image: "net_core_tpm"
    container_name: net_core_tpm
    ports:
      - '28081:8081'
      - '29000:9000'
      - '20080:80'
  net_core_http:
    build:
      context: HttpServer/.
      dockerfile: Dockerfile
    image: "net_core_http"
    container_name: net_core_http
  net_core_rest:
    build:
      context: RestServer/.
      dockerfile: Dockerfile
    image: "net_core_rest"
    container_name: net_core_rest
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
      - "/srv/mosquitto/config:/mosquitto/config"
      - "/srv/mosquitto/log:/mosquitto/log"
      - "/srv/mosquitto/data/:/mosquitto/data"
    ports:
      - "1883:1883"
  db_mysql:
    build:
      context: MySQL/.
      dockerfile: Dockerfile
    container_name: db_mysql
    image: "tpm_mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '23306:3306'