
services:
  py-tpm:
    build:
      context: Tpm/.
      dockerfile: Dockerfile
    image: "py-tpm"
    hostname: "py-tpm"
    depends_on:
      py-mysql:
        condition: service_started
      py-rabbit:
        condition: service_started
  py-rest:
    build:
      context: RestServer/.
      dockerfile: Dockerfile
    image: "py-rest"
    hostname: "py-rest"
    depends_on:
      py-mysql:
        condition: service_started
      py-tpm:
        condition: service_healthy
      py-rabbit:
        condition: service_started
  py-quote-generator:
    build:
      context: QuoteGenerator/.
      dockerfile: Dockerfile
    image: "py-quote-generator"
    hostname: "py-quote-generator"
    depends_on:
      py-rest:
        condition: service_healthy
      py-rabbit:
        condition: service_started
  py-mysql:
    build:
      context: MySQL/.
      dockerfile: Dockerfile
    hostname: "py-mysql"
    image: "py-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  py-rabbit:
    image: "rabbitmq:3-management"
    hostname: "py-rabbit"
    ports:
      - '25672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password