version: '3.8'
services:
  py-tpm:
    build:
      context: Tpm/.
      dockerfile: Dockerfile
    image: "py-tpm"
    container_name: py-tpm
    ports:
      - '31044:5005'  # debug port
      - '31883:5672'  # amqp-01 proxy port
      - '33306:3306'  # mysql-01 proxy port
      - '28081:8081'  # admin api port
      - '29000:9000'  # proxy port
      - '20080:80'  # tpm port
    depends_on:
      py-mysql:
        condition: service_started
      py-rabbit:
        condition: service_started
  py-rest:
    build:
      context: RestServer/.
      dockerfile: Dockerfile
    image: "py-rest"
    container_name: py-rest
    depends_on:
      py-mysql:
        condition: service_started
      py-tpm:
        condition: service_healthy
      py-quote-generator:
        condition: service_healthy
      py-rabbit:
        condition: service_started
  py-quote-generator:
    build:
      context: QuoteGenerator/.
      dockerfile: Dockerfile
    image: "py-quote-generator"
    container_name: py-quote-generator
    depends_on:
      py-rabbit:
        condition: service_started
  py-mysql:
    build:
      context: MySQL/.
      dockerfile: Dockerfile
    container_name: py-mysql
    image: "py-mysql"
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '23306:3306'
  py-rabbit:
    image: "rabbitmq:3-management"
    container_name: py-rabbit
    ports:
      - '25672:5672'
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: password